[server]
headless = true
enableCORS = false
enableXsrfProtection = true
runOnSave = true
maxUploadSize = 300
maxMessageSize = 300
fileWatcherType = "auto"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 0

[client]
toolbarMode = "minimal"
showErrorDetails = true
displayEnabled = true

[theme]
# ✨ Dynamic theme — detects user preference automatically
base = "auto"
primaryColor = "#305496"
backgroundColor = "#f9fafb"
secondaryBackgroundColor = "#eef1f6"
textColor = "#0f172a"
font = "sans serif"

# 🧠 Experimental UI
[ui]
hideTopBar = false
hideSidebar = false
animationSpeed = "fast"
cardShadows = true
roundedCorners = true
